/*
Copyright 2019 Bloomberg Finance LP.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	"github.com/bloomberg/solr-operator/pkg/apis/solr/v1beta1"
	"github.com/bloomberg/solr-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
)

// SolrBackupsGetter has a method to return a SolrBackupInterface.
// A group's client should implement this interface.
type SolrBackupsGetter interface {
	SolrBackups(namespace string) SolrBackupInterface
}

// SolrBackupInterface has methods to work with SolrBackup resources.
type SolrBackupInterface interface {
	Create(*v1beta1.SolrBackup) (*v1beta1.SolrBackup, error)
	Update(*v1beta1.SolrBackup) (*v1beta1.SolrBackup, error)
	UpdateStatus(*v1beta1.SolrBackup) (*v1beta1.SolrBackup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.SolrBackup, error)
	List(opts v1.ListOptions) (*v1beta1.SolrBackupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SolrBackup, err error)
	SolrBackupExpansion
}

// solrBackups implements SolrBackupInterface
type solrBackups struct {
	client rest.Interface
	ns     string
}

// newSolrBackups returns a SolrBackups
func newSolrBackups(c *SolrV1beta1Client, namespace string) *solrBackups {
	return &solrBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the solrBackup, and returns the corresponding solrBackup object, and an error if there is any.
func (c *solrBackups) Get(name string, options v1.GetOptions) (result *v1beta1.SolrBackup, err error) {
	result = &v1beta1.SolrBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("solrbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SolrBackups that match those selectors.
func (c *solrBackups) List(opts v1.ListOptions) (result *v1beta1.SolrBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.SolrBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("solrbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested solrBackups.
func (c *solrBackups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("solrbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a solrBackup and creates it.  Returns the server's representation of the solrBackup, and an error, if there is any.
func (c *solrBackups) Create(solrBackup *v1beta1.SolrBackup) (result *v1beta1.SolrBackup, err error) {
	result = &v1beta1.SolrBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("solrbackups").
		Body(solrBackup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a solrBackup and updates it. Returns the server's representation of the solrBackup, and an error, if there is any.
func (c *solrBackups) Update(solrBackup *v1beta1.SolrBackup) (result *v1beta1.SolrBackup, err error) {
	result = &v1beta1.SolrBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("solrbackups").
		Name(solrBackup.Name).
		Body(solrBackup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *solrBackups) UpdateStatus(solrBackup *v1beta1.SolrBackup) (result *v1beta1.SolrBackup, err error) {
	result = &v1beta1.SolrBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("solrbackups").
		Name(solrBackup.Name).
		SubResource("status").
		Body(solrBackup).
		Do().
		Into(result)
	return
}

// Delete takes name of the solrBackup and deletes it. Returns an error if one occurs.
func (c *solrBackups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("solrbackups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *solrBackups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("solrbackups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched solrBackup.
func (c *solrBackups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SolrBackup, err error) {
	result = &v1beta1.SolrBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("solrbackups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
