/*
Copyright 2019 Bloomberg Finance LP.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"github.com/bloomberg/solr-operator/pkg/apis/solr/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"
)

// FakeSolrClouds implements SolrCloudInterface
type FakeSolrClouds struct {
	Fake *FakeSolrV1beta1
	ns   string
}

var solrcloudsResource = schema.GroupVersionResource{Group: "solr.bloomberg.com", Version: "v1beta1", Resource: "solrclouds"}

var solrcloudsKind = schema.GroupVersionKind{Group: "solr.bloomberg.com", Version: "v1beta1", Kind: "SolrCloud"}

// Get takes name of the solrCloud, and returns the corresponding solrCloud object, and an error if there is any.
func (c *FakeSolrClouds) Get(name string, options v1.GetOptions) (result *v1beta1.SolrCloud, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(solrcloudsResource, c.ns, name), &v1beta1.SolrCloud{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrCloud), err
}

// List takes label and field selectors, and returns the list of SolrClouds that match those selectors.
func (c *FakeSolrClouds) List(opts v1.ListOptions) (result *v1beta1.SolrCloudList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(solrcloudsResource, solrcloudsKind, c.ns, opts), &v1beta1.SolrCloudList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SolrCloudList{ListMeta: obj.(*v1beta1.SolrCloudList).ListMeta}
	for _, item := range obj.(*v1beta1.SolrCloudList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested solrClouds.
func (c *FakeSolrClouds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(solrcloudsResource, c.ns, opts))

}

// Create takes the representation of a solrCloud and creates it.  Returns the server's representation of the solrCloud, and an error, if there is any.
func (c *FakeSolrClouds) Create(solrCloud *v1beta1.SolrCloud) (result *v1beta1.SolrCloud, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(solrcloudsResource, c.ns, solrCloud), &v1beta1.SolrCloud{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrCloud), err
}

// Update takes the representation of a solrCloud and updates it. Returns the server's representation of the solrCloud, and an error, if there is any.
func (c *FakeSolrClouds) Update(solrCloud *v1beta1.SolrCloud) (result *v1beta1.SolrCloud, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(solrcloudsResource, c.ns, solrCloud), &v1beta1.SolrCloud{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrCloud), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSolrClouds) UpdateStatus(solrCloud *v1beta1.SolrCloud) (*v1beta1.SolrCloud, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(solrcloudsResource, "status", c.ns, solrCloud), &v1beta1.SolrCloud{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrCloud), err
}

// Delete takes name of the solrCloud and deletes it. Returns an error if one occurs.
func (c *FakeSolrClouds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(solrcloudsResource, c.ns, name), &v1beta1.SolrCloud{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSolrClouds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(solrcloudsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.SolrCloudList{})
	return err
}

// Patch applies the patch and returns the patched solrCloud.
func (c *FakeSolrClouds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SolrCloud, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(solrcloudsResource, c.ns, name, pt, data, subresources...), &v1beta1.SolrCloud{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrCloud), err
}
