/*
Copyright 2019 Bloomberg Finance LP.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"github.com/bloomberg/solr-operator/pkg/apis/solr/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/testing"
)

// FakeSolrBackups implements SolrBackupInterface
type FakeSolrBackups struct {
	Fake *FakeSolrV1beta1
	ns   string
}

var solrbackupsResource = schema.GroupVersionResource{Group: "solr.bloomberg.com", Version: "v1beta1", Resource: "solrbackups"}

var solrbackupsKind = schema.GroupVersionKind{Group: "solr.bloomberg.com", Version: "v1beta1", Kind: "SolrBackup"}

// Get takes name of the solrBackup, and returns the corresponding solrBackup object, and an error if there is any.
func (c *FakeSolrBackups) Get(name string, options v1.GetOptions) (result *v1beta1.SolrBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(solrbackupsResource, c.ns, name), &v1beta1.SolrBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrBackup), err
}

// List takes label and field selectors, and returns the list of SolrBackups that match those selectors.
func (c *FakeSolrBackups) List(opts v1.ListOptions) (result *v1beta1.SolrBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(solrbackupsResource, solrbackupsKind, c.ns, opts), &v1beta1.SolrBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SolrBackupList{ListMeta: obj.(*v1beta1.SolrBackupList).ListMeta}
	for _, item := range obj.(*v1beta1.SolrBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested solrBackups.
func (c *FakeSolrBackups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(solrbackupsResource, c.ns, opts))

}

// Create takes the representation of a solrBackup and creates it.  Returns the server's representation of the solrBackup, and an error, if there is any.
func (c *FakeSolrBackups) Create(solrBackup *v1beta1.SolrBackup) (result *v1beta1.SolrBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(solrbackupsResource, c.ns, solrBackup), &v1beta1.SolrBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrBackup), err
}

// Update takes the representation of a solrBackup and updates it. Returns the server's representation of the solrBackup, and an error, if there is any.
func (c *FakeSolrBackups) Update(solrBackup *v1beta1.SolrBackup) (result *v1beta1.SolrBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(solrbackupsResource, c.ns, solrBackup), &v1beta1.SolrBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSolrBackups) UpdateStatus(solrBackup *v1beta1.SolrBackup) (*v1beta1.SolrBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(solrbackupsResource, "status", c.ns, solrBackup), &v1beta1.SolrBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrBackup), err
}

// Delete takes name of the solrBackup and deletes it. Returns an error if one occurs.
func (c *FakeSolrBackups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(solrbackupsResource, c.ns, name), &v1beta1.SolrBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSolrBackups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(solrbackupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.SolrBackupList{})
	return err
}

// Patch applies the patch and returns the patched solrBackup.
func (c *FakeSolrBackups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SolrBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(solrbackupsResource, c.ns, name, pt, data, subresources...), &v1beta1.SolrBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.SolrBackup), err
}
